export const category = [
  "Protest",
  "Animals",
  "Education",
  "Emergencies",
  "Natural Disaster",
  "Women Empowerment",
  "Rural Development",
  "Health and Disease",
  "Environmental Conservation",
];

export const countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas (the)",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory (the)",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands (the)",
  "Central African Republic (the)",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands (the)",
  "Colombia",
  "Comoros (the)",
  "Congo (the Democratic Republic of the)",
  "Congo (the)",
  "Cook Islands (the)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic (the)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (the) [Malvinas]",
  "Faroe Islands (the)",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories (the)",
  "Gabon",
  "Gambia (the)",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (the)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic (the)",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands (the)",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands (the)",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger (the)",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands (the)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines (the)",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation (the)",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan (the)",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands (the)",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates (the)",
  "United Kingdom of Great Britain and Northern Ireland (the)",
  "United States Minor Outlying Islands (the)",
  "United States of America (the)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
];

export const Teams = Object.freeze([
  {
    name: "Sabin Subedi",
    photo:
      "https://storage.googleapis.com/hello-de203.appspot.com/image-1623674681612.jpg",
    title: "Lead Developer",
    github: "https://github.com/Sabin-Subedi",
    linkedin: "https://www.linkedin.com/in/sabin-subedi-69517519a/",
    instagram: "https://www.instagram.com/dev_sabin/",
    web: "https://sabinsubedi.tech"
  },
  {
    name: "Nishu Shrestha",
    photo:
      "https://storage.googleapis.com/hello-de203.appspot.com/image-1625038790085.jpg",
    title: "UI/UX Engineer",
    github: "",
    linkedin: "https://www.linkedin.com/in/nishu-shrestha-625b2b1b3/",
    instagram: "https://www.instagram.com/ni.shu8343/",
  },
  {
    name: "Pratik Shrestha",
    photo:
      "https://storage.googleapis.com/hello-de203.appspot.com/image-1625038790085.jpg",
    title: "Data Analyst",
    github: "",
    linkedin: "https://www.linkedin.com/in/pratik-shrestha-3022551b2/",
    instagram: "https://www.instagram.com/pratikk._45/"
  },
  {
    name: "Saiman Adhikari",
    photo:
      "https://storage.googleapis.com/hello-de203.appspot.com/image-1625161866919.jpg",
    title: "Creative Head",
    github: "",
    linkedin: "https://www.linkedin.com/in/saiman-adhikari-09a425202/",
    instagram: "https://www.instagram.com/saiman.adhikari17/"
  },
  {
    name: "Pranish Khanal",
    photo:
      "https://storage.googleapis.com/hello-de203.appspot.com/image-1625163088957.jpg",
    title: "Project Manager",
    github: "",
    linkedin: "https://www.linkedin.com/in/pranish-khanal-5799721b2/",
    instagram: "https://www.instagram.com/pranis.khanal/"
  },
]);

export const categoryWithIcon = [
  {
    icon: "education.svg",
    category: "Education",
  },
  {
    icon: "health.svg",
    category: "Health and Disease",
  },
  {
    icon: "emergencies.svg",
    category: "Emergencies",
  },
  {
    icon: "environment.svg",
    category: "Environmental Conservation",
  },
  {
    icon: "protest.svg",
    category: "Protest",
  },
  {
    icon: "disaster.svg",
    category: "Natural Disaster",
  },
  {
    icon: "women.svg",
    category: "Women Empowerment",
  },
  {
    icon: "development.svg",
    category: "Rural Development",
  },
];

export const openedFor = [
  {
    title: "Donation",
    value: "donate",
  },
  {
    title: "Sponsorship",
    value: "sponsor",
  },
  {
    title: "Volunteering",
    value: "volunteer",
  },
];

export const features = Object.freeze([
  {
    title: "Secure",
    icon: "fal fa-shield-check",
    description:
      "Our Trust & Safety team works around the clock to protect against fraud.",
  },
  {
    title: "Social Reach",
    icon: "fal fa-analytics",
    description:
      "Harness the power of social media to spread your project and get more support.",
  },
  {
    title: "Community",
    icon: "fal fa-users",
    description:
      "The huge network of volunteers are always there to contribute to the projects.",
  },
  {
    title: "Transparent",
    icon: "fal fa-search-dollar",
    description:
      "The project created will be transparent to the members of the project to prevent fraud.",
  },
  {
    title: "Easy to Use",
    icon: "fal fa-hand-peace",
    description:
      "The creation and participation of projects is very easy, making this app a wonderful platform to use.",
  },
  {
    title: "Worldwide Leader",
    icon: "fal fa-globe",
    description:
      "WeREACH is trusted around the world for its simple, reliable platform.",
  },
]);
