export const LIST_PROJECTS_REQUEST = "LIST_PROJECTS_REQUEST";
export const LIST_PROJECTS_SUCCESS = "LIST_PROJECTS_SUCCESS";
export const LIST_PROJECTS_FAILURE = "LIST_PROJECTS_FAILURE";

export const PROJECT_DONATION_REQUEST = "PROJECT_DONATION_REQUEST";
export const PROJECT_DONATION_SUCCESS = "PROJECT_DONATION_SUCCESS";
export const PROJECT_DONATION_FAILURE = "PROJECT_DONATION_FAILURE";


export const PROJECT_CREATE_REQUEST = "PROJECT_CREATE_REQUEST";
export const PROJECT_CREATE_SUCCESS = "PROJECT_CREATE_SUCCESS";
export const PROJECT_CREATE_FAILURE = "PROJECT_CREATE_FAILURE";

export const PROJECT_BY_ID_REQUEST = "PROJECT_BY_ID_REQUEST";
export const PROJECT_BY_ID_SUCCESS = "PROJECT_BY_ID_SUCCESS";
export const PROJECT_BY_ID_FAILURE = "PROJECT_BY_ID_FAILURE";

